In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
df = pd.read_csv('../../data/tweets.csv')
df.head()

likes  retweets  replies  is_viral
0     10         2        0         0
1    123        14        5         1
2    203        34       29         1
3     23         2        3         0
4      1         0        0         0

In [6]:
df.shape


(100, 4)

In [7]:
df['is_viral'].value_counts()

is_viral
0    74
1    26
Name: count, dtype: int64

In [8]:
x = df.iloc[:,:-1].values
y = df.iloc[:, -1].values

array([[ 10,   2,   0],
       [123,  14,   5],
       [203,  34,  29],
       [ 23,   2,   3],
       [  1,   0,   0]])

In [9]:
x[0:5]

array([0, 1, 1, 0, 0])

In [10]:
y[0:5]

array([0, 1, 1, 0, 0])

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
x_train.shape

(80, 3)

In [12]:
clf = RandomForestClassifier()
clf.fit(x_train, y_train)

RandomForestClassifier()

In [31]:
viral_predict = clf.predict(([[50,10,9], [80,20,1]]))
viral_predict

array([0, 1])

In [14]:
x_test

array([[ 29,   2,   2],
       [ 65,   4,   2],
       [203,  34,  29],
       [ 28,   0,  10],
       [ 33,   3,   3],
       [ 50,   5,   5],
       [  0,   0,  11],
       [  0,   0,   5],
       [ 39,   3,   9],
       [ 48,   3,  20],
       [ 15,   2,   0],
       [  1,   0,   4],
       [ 34,   1,   1],
       [ 52,  10,   1],
       [ 38,   4,   4],
       [144,  20,   8],
       [  9,   1,   1],
       [167,  22,  10],
       [ 11,   2,   4],
       [298,  38,  32]])

In [15]:
y_test

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1])

In [20]:
y_pred = clf.predict(x_test)
y_pred

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1])

In [21]:
accuracy_score(y_test, y_pred)

1.0